## 广播机制
广播机制（broadcasting）使不同形状的张量在进行算术操作时能够自动扩展为相同的形状。
### 广播机制规则
广播机制遵循以下规则：
- 1.如果两个张量的维度数量不同，则在较小维度的张量前面添加尺寸为1的维度，直到两个张量的维度数量相同。
- 2.从最后一个维度（即最右边的维度）开始，依次比较每一个维度：
    - 如果两个张量在某个维度的长度相同，或者其中一个张量在该维度的长度为1，则认为它们在该维度是兼容的，可以进行广播。   
    - 如果在任何维度上，它们的长度不相同且不为1，则会引发错误，表示它们不能广播。
使用广播的注意事项
- 内存效率：广播不会实际复制数据，而是通过增加步长来实现，因此在内存上是高效的。
- 广播限制：并不是所有形状的张量都可以广播，如果形状不兼容，PyTorch会抛出错误。

In [2]:
import torch

In [3]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [4]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片

就像在任何其他Python数组中一样，张量中的元素可以通过索引访问。
与任何Python数组一样：第一个元素的索引是0，最后一个元素索引是-1；
可以指定范围以包含第一个元素和最后一个之前的元素。

如下所示，我们[**可以用`[-1]`选择最后一个元素，可以用`[1:3]`选择第二个和第三个元素**]：

如果我们想[**为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。**]
例如，`[0:2, :]`访问第1行和第2行，其中“:”代表沿轴1（列）的所有元素。